name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:       # <-- Job CI
    runs-on: ubuntu-latest
    steps:
      # checkout, install, lint, test

  docker:                # <-- Job CD
    runs-on: ubuntu-latest
    needs: build-test-lint   # espera a que CI pase
    steps:
      # checkout, docker login, build & push
